import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'

const ROOT = join(__dirname, '..')
const OUT = join(ROOT, 'web', 'lib')

/** Only the pieces the UI calls, so the bundle does not carry the whole ABI. */
const WANTED: Record<string, string[]> = {
  CreditRegistry: [
    'scoreOf',
    'standingOf',
    'markets',
    'recordRepayment',
    'hasClaimed',
    'RepaymentRecorded'
  ],
  CreditLine: [
    'limitOf',
    'owedBy',
    'loanOf',
    'available',
    'ceiling',
    'rateBps',
    'term',
    'draw',
    'repay',
    'asset',
    'Drawn',
    'Repaid'
  ],
  TestUSD: ['balanceOf', 'approve', 'allowance', 'decimals', 'symbol', 'mint']
}

function abiOf(name: string, path: string) {
  const artifact = JSON.parse(readFileSync(join(ROOT, 'artifacts', path), 'utf8'))
  const keep = WANTED[name]
  return artifact.abi.filter((f: any) => !f.name || keep.includes(f.name))
}

function main() {
  const deployments = JSON.parse(readFileSync(join(ROOT, 'deployments.json'), 'utf8'))

  const abis = {
    CreditRegistry: abiOf('CreditRegistry', 'contracts/CreditRegistry.sol/CreditRegistry.json'),
    CreditLine: abiOf('CreditLine', 'contracts/CreditLine.sol/CreditLine.json'),
    TestUSD: abiOf('TestUSD', 'contracts/source/TestUSD.sol/TestUSD.json')
  }

  const cc = deployments.creditcoinTestnet ?? {}
  const sepolia = deployments.sepolia ?? {}

  const body = `// Generated by scripts/export-abi.ts. Do not edit.

export const creditcoin = {
  id: 102031,
  name: 'Creditcoin Testnet',
  rpc: 'https://rpc.cc3-testnet.creditcoin.network',
  explorer: 'https://creditcoin-testnet.blockscout.com'
} as const

export const sourceChain = {
  id: 11155111,
  name: 'Sepolia',
  explorer: 'https://sepolia.etherscan.io',
  chainKey: 1
} as const

export const addresses = {
  registry: '${cc.CreditRegistry ?? ''}',
  line: '${cc.CreditLine ?? ''}',
  usd: '${cc.TestUSD ?? ''}',
  sourcePool: '${sepolia.DemoLendingPool ?? ''}',
  aavePool: '${sepolia.AaveV3Pool ?? ''}',
  cometPool: '${sepolia.CompoundV3Comet ?? ''}'
} as const

export const registryAbi = ${JSON.stringify(abis.CreditRegistry, null, 2)} as const

export const lineAbi = ${JSON.stringify(abis.CreditLine, null, 2)} as const

export const erc20Abi = ${JSON.stringify(abis.TestUSD, null, 2)} as const
`

  mkdirSync(OUT, { recursive: true })
  writeFileSync(join(OUT, 'contracts.ts'), body)
  console.log(`wrote web/lib/contracts.ts`)
  console.log(`  registry ${addressesLine(cc.CreditRegistry)}`)
  console.log(`  line     ${addressesLine(cc.CreditLine)}`)
  console.log(`  usd      ${addressesLine(cc.TestUSD)}`)
  console.log(`  pool     ${addressesLine(sepolia.DemoLendingPool)}`)
}

function addressesLine(v?: string) {
  return v ?? 'MISSING'
}

main()

